"""Adds role field to usermodel

Revision ID: b5fff00ce1cc
Revises: 7a4bd97863b4
Create Date: 2026-08-29 13:25:44.402171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from users.models import UserRole

# revision identifiers, used by Alembic.
revision: str = 'b5fff00ce1cc'
down_revision: Union[str, Sequence[str], None] = '7a4bd97863b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

userrole_enum = sa.Enum(UserRole, name="userrole")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
